###############################################################################
# Created by write_sdc
###############################################################################
current_design io_pad_wrapper
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 10.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {core_dout}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pad_din_raw}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reg_addr[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reg_addr[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reg_wdata[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reg_wdata[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reg_wdata[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reg_wdata[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reg_wdata[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reg_wdata[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reg_wdata[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reg_wdata[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reg_we}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rst_n}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {core_din}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pad_dout}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pad_oe}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pad_pd_en}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pad_pu_en}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pad_schmitt_en}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pad_slew[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pad_slew[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reg_rdata[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reg_rdata[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reg_rdata[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reg_rdata[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reg_rdata[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reg_rdata[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reg_rdata[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reg_rdata[7]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {core_din}]
set_load -pin_load 0.0334 [get_ports {pad_dout}]
set_load -pin_load 0.0334 [get_ports {pad_oe}]
set_load -pin_load 0.0334 [get_ports {pad_pd_en}]
set_load -pin_load 0.0334 [get_ports {pad_pu_en}]
set_load -pin_load 0.0334 [get_ports {pad_schmitt_en}]
set_load -pin_load 0.0334 [get_ports {pad_slew[1]}]
set_load -pin_load 0.0334 [get_ports {pad_slew[0]}]
set_load -pin_load 0.0334 [get_ports {reg_rdata[7]}]
set_load -pin_load 0.0334 [get_ports {reg_rdata[6]}]
set_load -pin_load 0.0334 [get_ports {reg_rdata[5]}]
set_load -pin_load 0.0334 [get_ports {reg_rdata[4]}]
set_load -pin_load 0.0334 [get_ports {reg_rdata[3]}]
set_load -pin_load 0.0334 [get_ports {reg_rdata[2]}]
set_load -pin_load 0.0334 [get_ports {reg_rdata[1]}]
set_load -pin_load 0.0334 [get_ports {reg_rdata[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {core_dout}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {pad_din_raw}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {reg_we}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rst_n}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {reg_addr[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {reg_addr[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {reg_wdata[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {reg_wdata[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {reg_wdata[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {reg_wdata[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {reg_wdata[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {reg_wdata[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {reg_wdata[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {reg_wdata[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 10.0000 [current_design]
